theme = "tabi"
title = "Davide Andreoli"

# The URL the site will be built for
base_url = "https://davide-andreoli.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
style = "class"


[extra]

skin = "teal"
show_selected_language_code_in_language_switcher = true
email = "ZGF2aWRlLmFuZHJlb2xpQGljbG91ZC5jb20="
quick_navigation_buttons = true
copy_button = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
]

socials = [
    { name = "github", url = "https://github.com/davide-andreoli/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/davide-andreoli-140b35154/", icon = "linkedin" }
]

footer_menu = [
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]

